### ISSUE TITLE
快速编辑购买菜单无法保存

### ISSUE THREAD

**Issue by Terli** [ltndkl/Counter-Strike-Augmented-Edition#6]
OS:Win10 Pro  2004
窗口化游戏
杀软已经将hl和csae放入信任区

主界面中编辑武器后点击“返回目录”，未保存设置内容。

**Comment by ltndkl** [comment]
确认一下 `platform\config\Favorite.vdf` 的修改时间是否正常

**Comment by Terli** [comment]
已恢复，原因不明，可能和我在master启动器进入有关系，但是之后在master启动器中编辑武器保存变为正常

**Comment by ltndkl** [comment]
如有相关的后续问题请重新开启此 issue。
