### ISSUE TITLE
cl_minmodels 1 bug

### ISSUE THREAD

**Issue by Target5150** [ltndkl/Counter-Strike-Augmented-Edition#7]
![ID VC1PM0WK_ZQRGLVG161E](https://user-images.githubusercontent.com/42076548/148017203-4ef380c6-23d5-4d2b-988a-9af2756af453.jpg)
如图。

**Comment by ltndkl** [comment]
已解决，同时限制该命令无法在生化模式下使用。
![image](https://user-images.githubusercontent.com/13776187/148018869-9ba57910-d6a3-4394-81b8-85f5ac55a1ba.png)
